
# General

IMAGE_SIZE = 64

INPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, 3)
OUTPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, 3)

# Images

DUPLICATE_IMAGES = 1
BUFFER_SIZE = 8100
BATCH_SIZE = 128

# Noise

import tensorflow as tf

NOISE_LEVELS = 128

BETA_MIN = 0.0001
BETA_MAX = 0.002
NOISING_SCHEDULE = tf.linspace(BETA_MIN, BETA_MAX, NOISE_LEVELS)
